2º Practica - Divide y Vencerás: maximo_minimo_DyV.cpp File Reference
maximo_minimo_DyV.cpp File Reference
Programa para encontrar el máximo y mínimo de un vector utilizando la técnica de Divide y Vencerás.
#include <iostream>
#include <omp.h>
Classes
struct ResultadoMaxMin
Structura para almacenar los índices del máximo y mínimo encontrados en un segmento del vector.
Functions
ResultadoMaxMin encontrar_maximo_minimo_segmento (int *v, int inicio, int fin)
Función para encontrar el máximo y mínimo en un segmento del vector.
void encontrar_maximo_minimo (int *v, int n, int &max_idx, int &min_idx)
Función recursiva para encontrar el máximo y mínimo en un vector utilizando OpenMP.
int main (int argc, char const *argv[])
Detailed Description
Programa para encontrar el máximo y mínimo de un vector utilizando la técnica de Divide y Vencerás.
Este programa utiliza OpenMP para paralelizar la búsqueda del máximo y mínimo en un vector de enteros. La eficiencia teórica en el peor de los casos es O(n log n), y en el mejor de los casos es O(n). El algoritmo divide el vector en dos mitades, encuentra el máximo y mínimo en cada mitad y combina los resultados. Se utiliza la directiva #pragma omp parallel sections para paralelizar la búsqueda en ambas mitades, y se combinan las soluciones para obtener el resultado final. El programa también incluye una estructura ResultadoMaxMin para almacenar los índices del máximo y mínimo encontrados.
Author
Enrique Pinazo Moreno
Date
2025-04-15
Definition in file maximo_minimo_DyV.cpp.
Function Documentation
encontrar_maximo_minimo()
void encontrar_maximo_minimo (int * v, int n, int & max_idx, int & min_idx)
Función recursiva para encontrar el máximo y mínimo en un vector utilizando OpenMP.
Parameters
v Vector de enteros.
n Tamaño del vector.
max_idx Índice del máximo encontrado.
min_idx Índice del mínimo encontrado.
Se plantean los casos base para un elemento y dos elementos, para evitar la recursión innecesaria.
Caso base para dos elementos
Dividir el vector en dos mitades y buscar el máximo y mínimo en paralelo
Comparar los resultados de ambas mitades
Definition at line 67 of file maximo_minimo_DyV.cpp.
References encontrar_maximo_minimo_segmento(), ResultadoMaxMin::max_idx, and ResultadoMaxMin::min_idx.
Referenced by main().
encontrar_maximo_minimo_segmento()
ResultadoMaxMin encontrar_maximo_minimo_segmento (int * v, int inicio, int fin)
Función para encontrar el máximo y mínimo en un segmento del vector.
Parameters
v Vector de enteros.
inicio Índice de inicio del segmento.
fin Índice de fin del segmento.
Returns
Los indices del valor maximo y minimo.
Aquí se busca el máximo en la mitad
Aquí se busca el mínimo en la mitad
Almacenar los índices del máximo y mínimo encontrados
Definition at line 35 of file maximo_minimo_DyV.cpp.
References ResultadoMaxMin::max_idx, and ResultadoMaxMin::min_idx.
Referenced by encontrar_maximo_minimo().
main()
int main (int argc, char const * argv[])
Tamaño del vector
Declaración de los elementos del vector/
...
Variables para almacenar los índices del máximo y mínimo
Llamada a la función para encontrar el máximo y mínimo
Mostrar el vector
Mostrar los resultados
Liberar la memoria del vector dinámico
Definition at line 126 of file maximo_minimo_DyV.cpp.
References encontrar_maximo_minimo().