2º Practica - Divide y Vencerás: sub_sumaMaxima_DyV.cpp File Reference
sub_sumaMaxima_DyV.cpp File Reference
Algoritmo para encontrar el subvector con la suma máxima utilizando el método de Divide y Vencerás.
#include <iostream>
#include <climits>
Classes
struct ResultadoSubSumMax
Estructura para almacenar el resultado de la suma máxima de un subvector.
Functions
ResultadoSubSumMax max_cruce_sum (int v[], int inicio, int medio, int fin)
Función para calcular la suma máxima cruzando el medio.
ResultadoSubSumMax max_subvector (int v[], int inicio, int fin)
Función recursiva para encontrar el subvector con la suma máxima.
int main (int argc, char const *argv[])
Detailed Description
Algoritmo para encontrar el subvector con la suma máxima utilizando el método de Divide y Vencerás.
Este algoritmo utiliza la técnica de Divide y Vencerás para encontrar el subvector con la suma máxima en un vector de enteros. Se divide el vector en dos mitades, se calcula la suma máxima en cada mitad y se combina el resultado. La eficiencia teórica en el peor de los casos es O(n log n), y en el mejor de los casos es O(n).
Author
Enrique Pinazo Moreno
Date
2025-04-15
Definition in file sub_sumaMaxima_DyV.cpp.
Function Documentation
main()
int main (int argc, char const * argv[])
Vector que cruza el punto medio
Calcular el tamaño del vector
Llamada a la función para encontrar el subvector con la suma máxima
Definition at line 98 of file sub_sumaMaxima_DyV.cpp.
References ResultadoSubSumMax::fin, ResultadoSubSumMax::inicio, max_subvector(), and ResultadoSubSumMax::suma.
max_cruce_sum()
ResultadoSubSumMax max_cruce_sum (int v[], int inicio, int medio, int fin)
Función para calcular la suma máxima cruzando el medio.
Parameters
v Vector de enteros
inicio Índice de inicio del subvector
medio Índice medio del subvector
fin Índice de fin del subvector
Returns
ResultadoSubSumMax Estructura que contiene la suma máxima y los índices de inicio y fin del subvector
Calcular la suma máxima en la parte izquierda
Calcular la suma máxima en la parte derecha
Definition at line 36 of file sub_sumaMaxima_DyV.cpp.
Referenced by max_subvector().
max_subvector()
ResultadoSubSumMax max_subvector (int v[], int inicio, int fin)
Función recursiva para encontrar el subvector con la suma máxima.
Parameters
v Vector de enteros
inicio Índice de inicio del subvector
fin Índice de fin del subvector
Returns
ResultadoSubSumMax Estructura que contiene la suma máxima y los índices de inicio y fin del subvector
Definition at line 73 of file sub_sumaMaxima_DyV.cpp.
References max_cruce_sum(), max_subvector(), and ResultadoSubSumMax::suma.
Referenced by main(), and max_subvector().